export enum DUMMY_ENUMS {
  COOKIE_ACCESS_EXPIRY = 'COOKIE_ACCESS_EXPIRY',
  COOKIE_REFRESH_EXPIRY = 'COOKIE_REFRESH_EXPIRY',
  HASH_ALGORITHM = 'HASH_ALGORITHM',
  JWT_SECRET = 'JWT_SECRET',
  JWT_ACCESS_EXPIRY = 'JWT_ACCESS_EXPIRY',
  ACCESS_TOKEN = 'access_token',
  REFRESH_TOKEN = 'refresh_token',
}
